# .github/workflows/release.yml

name: Publish to JitPack

on:
  push:
    branches:
      - master # 或者 main, feat-kotlin 等
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17 # 将名称也改为17，更清晰
        uses: actions/setup-java@v4
        with:
          java-version: '17' # <<<<<< 这里从 '11' 修改为 '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish with Gradle
        run: ./gradlew assemble publishAllPublicationsToMavenRepository

      - name: Trigger JitPack Build (Optional - Manual Trigger Example)
        run: echo "JitPack会自动从GitHub仓库拉取代码进行构建，无需在此手动触发。"